import type { AnalysisData } from "@/components/AnalysisDashboard";

export const PREDICT_ENDPOINT =
  (import.meta.env.VITE_TRUSTLENS_API as string | undefined) ??
  "http://127.0.0.1:8000/predict";

export interface PredictResponse {
  prediction: string;   // e.g. "AI Generated" | "Real Image"
  confidence: number;   // 0–100
}

/** Pure mapper — exported for unit testing. */
export function mapPrediction(
  res: PredictResponse,
  file: { name: string; size: number },
  previewUrl: string,
): AnalysisData {
  const isAI = /ai|fake|generated|synthetic/i.test(res.prediction);
  const confidence = Math.max(0, Math.min(100, Math.round(res.confidence)));
  // Trust score: how likely it is authentic
  const score = isAI ? Math.max(0, 100 - confidence) : confidence;

  const risk = score >= 75 ? "Low" : score >= 50 ? "Medium" : "High";
  const tone = (v: number) =>
    (v >= 75 ? "good" : v >= 50 ? "warn" : "bad") as "good" | "warn" | "bad";

  const findings = isAI
    ? [
        `Model verdict: ${res.prediction}`,
        `Backend reports ${confidence}% confidence in AI-generation`,
        "Synthesis fingerprints detected by forensic model",
        "Manual verification strongly recommended before publication",
      ]
    : [
        `Model verdict: ${res.prediction}`,
        `Backend reports ${confidence}% confidence in authenticity`,
        "No synthesis fingerprints detected by forensic model",
        "Asset passes baseline TrustLens integrity checks",
      ];

  return {
    kind: "image",
    fileName: file.name,
    previewUrl,
    score,
    confidence,
    metrics: [
      { label: "Trust Score", value: score, tone: tone(score) },
      { label: "AI Generated Probability", value: isAI ? confidence : 100 - confidence, tone: isAI ? "bad" : "good" },
      { label: "Authenticity Confidence", value: isAI ? 100 - confidence : confidence, tone: tone(isAI ? 100 - confidence : confidence) },
      { label: "Model Confidence", value: confidence, tone: "neutral" },
    ],
    findings: [
      ...findings,
      `Risk Level: ${risk}`,
      `Prediction: ${res.prediction}`,
    ],
  };
}

export async function analyzeFile(
  file: File,
  _kind: "image" | "video" | "audio" = "image",
): Promise<AnalysisData> {
  const previewUrl = URL.createObjectURL(file);
  const form = new FormData();
  form.append("file", file);

  const res = await fetch(PREDICT_ENDPOINT, { method: "POST", body: form });
  if (!res.ok) {
    throw new Error(`Backend returned ${res.status} ${res.statusText}`);
  }
  const json = (await res.json()) as PredictResponse;
  if (typeof json?.prediction !== "string" || typeof json?.confidence !== "number") {
    throw new Error("Invalid response shape from backend");
  }
  return mapPrediction(json, file, previewUrl);
}

export function downloadReport(data: AnalysisData) {
  const verdict = data.score >= 75 ? "Likely Authentic" : data.score >= 50 ? "Needs Review" : "AI Generated";
  const risk = data.score >= 75 ? "Low" : data.score >= 50 ? "Medium" : "High";
  const lines = [
    "TRUSTLENS AI — FORENSIC ANALYSIS REPORT",
    "==========================================",
    "",
    `File:        ${data.fileName}`,
    `Type:        ${data.kind.toUpperCase()}`,
    `Date:        ${new Date().toLocaleString()}`,
    "",
    "VERDICT",
    "------------------------------------------",
    `Result:           ${verdict}`,
    `Trust Score:      ${data.score}/100`,
    `Confidence:       ${data.confidence}%`,
    `Risk Level:       ${risk}`,
    "",
    "DETECTION METRICS",
    "------------------------------------------",
    ...data.metrics.map((m) => `  • ${m.label.padEnd(28)} ${m.value}%`),
    "",
    "KEY FINDINGS",
    "------------------------------------------",
    ...data.findings.map((f) => `  - ${f}`),
    "",
    "==========================================",
    "Generated by TrustLens AI",
  ];
  const blob = new Blob([lines.join("\n")], { type: "text/plain" });
  const url = URL.createObjectURL(blob);
  const a = document.createElement("a");
  a.href = url;
  a.download = `TrustLens-Report-${data.fileName.replace(/\.[^.]+$/, "")}.txt`;
  a.click();
  URL.revokeObjectURL(url);
}
